service: kezzle-clip-serving
frameworkVersion: "3"

provider:
    name: aws
    runtime: python3.11
    stage: dev
    region: ap-northeast-2
    ecr:
        images:
            koclip-image:
                path: ./ko_image_vectorizer
                platform: linux/amd64
            koclip-keyword-search:
                path: ./ko_text_search
                platform: linux/amd64
            koclip-keyword-search-pagination:
                path: ./ko_text_search_pagination
                platform: linux/amd64

custom:
    mongo: ${file(./mongo-env.yml)}

functions:
    ko-image-vectorizer:
        architecture: x86_64
        image:
            name: koclip-image
        timeout: 180
        memorySize: 1536
    ko-keyword-search:
        architecture: x86_64
        image:
            name: koclip-keyword-search
        events:
            - http:
                  path: /cakes/ko-search
                  method: get
        timeout: 60
        memorySize: 1536
        environment: ${self:custom.mongo}
        fileSystemConfig:
            localMountPath: ${file(./efs-env.yml):MOUNT_PATH}
            arn: ${file(./efs-env.yml):EFSARN}
        vpc:
            securityGroupIds:
                - ${file(./efs-env.yml):SGID}
            subnetIds:
                - ${file(./efs-env.yml):SUBNETID1}
                - ${file(./efs-env.yml):SUBNETID2}
    ko-keyword-search-pagination:
        architecture: x86_64
        image:
            name: koclip-keyword-search-pagination
        events:
            - http:
                  path: /cakes/ko-search-page
                  method: get
        timeout: 60
        memorySize: 1536
        environment: ${self:custom.mongo}
        fileSystemConfig:
            localMountPath: ${file(./efs-env.yml):MOUNT_PATH}
            arn: ${file(./efs-env.yml):EFSARN}
        vpc:
            securityGroupIds:
                - ${file(./efs-env.yml):SGID}
            subnetIds:
                - ${file(./efs-env.yml):SUBNETID1}
                - ${file(./efs-env.yml):SUBNETID2}
